name: train-test

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest

    steps:
      - uses: actions/checkout@v2

      - name: cml_run
        shell: bash
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TB_CREDENTIALS: ${{ secrets.TB_CREDENTIALS }}
        run: |
          apt-get --purge remove -y dvc

          pip install "git+https://github.com/iterative/dvc#egg=dvc[s3]"
          dvc -V

          dvc pull --run-cache
          
          echo 'CML' > report.md

          # TB credentials issue
          #pip install tensorboard
          cml-tensorboard-dev --logdir logs --md --name "Go to TB" >> report.md
          cml-send-comment report.md
          
          pip install -r requirements.txt
          dvc repro

          dvc push --run-cache

          cml-send-github-check report.md

